### PR TITLE
Set content length

### PR DESCRIPTION
**Pull request by jonasfj**

### CODE REVIEW

**Comment by jhford** [comment]
I have this change in another pull request.  As it stands, it does not work because in the unit test suits, the gzip and deflate encoded resources are uploading more bytes than the original content length, which means that there's something going on here that's needing to be looked into:wq

**Comment by jonasfj** [comment]
@jhford,
Ah, of course the request library will gzipped decode if it was encoded...
We should not do that, it slows things down and makes the download bigger..
But we must then propagate the content-encoding: gzip header.

Den 13. okt. 2016 7.13 AM skrev "John Ford" <notifications@github.com>:

**Comment by jhford** [comment]
yep, and that's the complexity here :)

**Comment by jhford** [comment]
but it could also be the requests library counting the number of bytes incorrectly...

**Pull request closed without merging**
